apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k5b5nqfpd-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:1e30e3a79a249de88f1f8e28fe7a52c5d27556e4@sha256:4bcb64a2f9db3b7ceaf5c28fd92fbb8f31ab8d28212303fa8811367ebe9b196c
          name: container-image
