apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k5b5nqfpd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k5b5nqfpd-go 
  name: k5b5nqfpd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: k5b5nqfpd-go 
